Package and module cleanup (#183)

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -50,13 +50,14 @@ jobs:
       - run: python -m pip install uv
 
       - name: Run Pytests for Codecov Test Analytics
+        id: run_tests
         working-directory: python
         run: |
           uv run pytest --disable-warnings --cov --junitxml=junit.xml -o junit_family=legacy
         continue-on-error: true
 
       - name: Run Pytests for Codecov Coverage
-        id: run_tests
+        id: run_tests_coverage
         working-directory: python
         run: |
           uv run pytest --disable-warnings --cov --cov-branch --cov-report=xml
@@ -82,6 +83,8 @@ jobs:
           files: "python/coverage.xml"
           disable_search: 'true'
 
-      - name: Fail if tests failed
-        if: steps.run_tests.outputs.exit_code != '0'
-        run: exit 1
+      - name: Check if tests failed
+        if: steps.run_tests.outcome == 'failure' || steps.run_tests_coverage.outcome == 'failure'
+        run: |
+          echo "One or more test steps failed"
+          exit 1
